export const TYPES = {
    VALIDATE_NAME : 'VALIDATE_NAME',
    VALIDATE_CEDULA: 'VALIDATE_CEDULA',
    VALIDATE_CORREO: 'VALIDATE_CORREO',
    VALIDATE_PASS: 'VALIDATE_PASS',
    CONFIRM_PASS: 'CONFIRM_PASS',
    VALIDATE_FECHA: 'VALIDATE_FECHA',
    VALIDATE_CIUDAD: 'VALIDATE_CIUDAD',
}